<?php
/**
 * A Magento 2 module named Magestat/CookieLawBanner
 * Copyright (C) 2018 Magestat
 *
 * This file included in Magestat/CookieLawBanner is licensed under OSL 3.0
 *
 * http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * Please see LICENSE.txt for the full text of the OSL 3.0 license
 *
 *
 * @var $block \Magestat\CookieLawBanner\Block\CookieLawBanner
 */
?>
<div id="magestat-cookie-law-banner" data-bind="scope:'magestat-cookie-law-banner'">
    <div class="content-inner-container">
        <div class="banner-title">
            <h3><?= /* @escapeNotVerified */ $block->getTitle() ?></h3>
        </div>
        <div class="banner-content">
            <p class="cookie-content"><?= /* @escapeNotVerified */ $block->getMessage() ?></p>
            <p class="more-info-content">
                <a class="link" href="<?= /* @escapeNotVerified */ $block->getInfoLink() ?>">
                    <em><?= /* @escapeNotVerified */ $block->getInfoMessage() ?></em>
                </a>
            </p>
        </div>
        <div class="banner-button">
            <button class="action primary button-accept">
                <span><?= /* @escapeNotVerified */ $block->getButton() ?></span>
            </button>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
    "#magestat-cookie-law-banner": {
        "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout(); ?>
    }
}
</script>