<?php
/**
 * A Magento 2 module named Magestat/CookieNotice
 * Copyright (C) 2018 Magestat
 *
 * This file included in Magestat/CookieNotice is licensed under OSL 3.0
 *
 * http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * Please see LICENSE.txt for the full text of the OSL 3.0 license
 *
 *
 * $block \Magestat\CookieNotice\Block\CookieNotice
 */
?>
<div class="cookie-notice">
    <div class="content-inner-container">
        <div class="banner-title">
            <h5><?= $block->getTitle() ?></h5>
        </div>
        <div class="banner-content">
            <p><?= $block->getMessage() ?></p>
            <p><em><a href="<?= $block->getInfoLink() ?>"><?= $block->getInfoMessage() ?></a></em></p>
        </div>
        <div class="banner-button">
            <button class="button-accept"><?= $block->getButton() ?></button>
        </div>
    </div>
</div>